import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <div>
        <a href="https://github.com/HunterGerlach/multi-stage-deployment-example-nextjs-github-pages-staging">
          <Image
            decoding="async"
            loading="lazy"
            width="149"
            height="149"
            src="./forkme_left_green_007200.png"
            className="attachment-full size-full"
            alt="Fork me on GitHub"
            data-recalc-dims="1"
          />
        </a>
      </div>
      <div className={styles.header}>
        <Image
          priority
          src="./james-orr-38CyKJ1hkQc-unsplash.jpg"
          alt="Multiple legos of the same type"
          width="640"
          height="420"
        />
      </div>
      <main className={styles.main}>
        <h1>Multi-Stage Deployment Example with Next.JS and Github Pages</h1>
        <p>This repository contains an example of deploying a Next.JS application to multiple stages or environments using GitHub Pages and GitHub Actions. It consists of two repositories:</p>
        <h2>## multi-stage-deployment-example-nextjs-github-pages-staging</h2>
        <p>This repository contains the code for the Next.JS application that is deployed to the staging environment via GitHub Pages. It includes a configuration file that specifies the URL of the staging environment and any other necessary details.</p>
        <p>To deploy the application to the staging environment, you can push your code changes to the `main` branch of this repository. The application will be automatically deployed to the staging environment by GitHub Pages.</p>
        <h2>## multi-stage-deployment-example-nextjs-github-pages-production</h2>
        <p>This repository contains the code and configuration for the GitHub Actions workflow that deploys the Next.JS application to the production environment. It includes a configuration file that specifies the URL of the production environment and any other necessary details.</p>
        <p>To deploy the application to the production environment, you can create a new release of the application in the staging repo and tag it with the desired version number. The GitHub Actions workflow will automatically deploy the application to the production environment.</p>
        <p>To use this example in your own project, you can fork these repositories and customize them to fit your specific needs.
        </p>
        <div className={styles.grid}>
          <a
            href="https://www.huntergerlach.com"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              HunterGerlach.com <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn more about this project and others at www.HunterGerlach.com.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
